#!/usr/bin/env bash
#
# Guard against FlexAID∆S palette v1 creeping back into the site.
#
# WHY THIS EXISTS AS A SCRIPT AND NOT AN AD-HOC GREP
# --------------------------------------------------
# The v2 migration was verified with a one-off `grep -E '#22D3EE(?![0-9A-Fa-f])'`.
# POSIX ERE has no lookahead, so grep -E matched the literal characters "(?!..."
# and found nothing — reporting a clean tree that had never actually been
# checked. The conclusion happened to be right; the evidence was worthless.
#
# So this script does two things a bare grep does not:
#   1. asserts up front that the regex engine supports what the patterns need,
#      and refuses to run rather than silently under-matching;
#   2. self-tests every pattern against a known-bad fixture, so a pattern that
#      stops matching fails the build instead of passing quietly.
#
# A check that cannot fail is not a check.
#
# Usage:  scripts/check-palette-v2.sh            # scan the tree
#         scripts/check-palette-v2.sh --self-test # only prove the checks work

set -euo pipefail
cd "$(dirname "$0")/.."

# ── scope ────────────────────────────────────────────────────────────────
# Excluded, deliberately:
#   design/palette-v2/   the exploration board — its early rounds SHOW the
#                        retired colours on purpose; that is their subject
#   transit/             generated by publish-transit from the Transit repo;
#                        fix palette drift at that source, not here
#   style.css            the design guide states this is a separate burgundy
#                        exploration and NOT the live look
#   assets/index-*.css   hashed build artifact, source not in this repo
EXCLUDE_RE='^(design/palette-v2/|transit/|style\.css$|assets/index-[A-Za-z0-9_-]+\.css$)'
BINARY_RE='\.(png|jpe?g|gif|ico|pdf|woff2?|ttf|otf|zip)$'

# ── the v1 palette, in every syntax it is written in ─────────────────────
# Retired hexes. #A78BFA is deliberately NOT here: in v2 it is a legitimate
# token (--kw-docking, the lighter violet). It is caught by BINDINGS below
# only when re-bound to --terra, which is what it meant in v1.
V1_HEX='22D3EE|FBBF24|FDE68A|8B1A4A|0a0e14|d4dced|8a93a8|67E8F9|FCD34D|5046D6|2a9aa8|C2456F|DA2F63|6E7C99|FF2600'
# Matches #RRGGBB and #RRGGBBAA, but never a longer hex run.
HEX_RE="(?i)#(${V1_HEX})([0-9A-Fa-f]{2})?(?![0-9A-Fa-f])"
# rgb()/rgba(), comma- or space-separated. The space form is how the v2 sweep
# first missed `rgb(34 211 238 / 0.07)` in the Transit atlas.
RGB_RE='rgba?\(\s*(34[\s,]+211[\s,]+238|251[\s,]+191[\s,]+36|167[\s,]+139[\s,]+250|139[\s,]+26[\s,]+74|10[\s,]+14[\s,]+20|16[\s,]+20[\s,]+28|12[\s,]+16[\s,]+22)\b'
# A v2 colour bound to the quantity it meant in v1 is still a v1 palette.
BINDINGS_RE='--terra:\s*#A78BFA'

# Prose that documents the retired set rather than using it. Wrap such a
# block in these markers; a colour inside a comment is never rendered, and
# the retired list has to be allowed to name the colours it retires.
IGNORE_START='palette-check-ignore-start'
IGNORE_END='palette-check-ignore-end'

fail=0
note() { printf '  %s\n' "$*"; }

# ── 0. the regex engine must actually support lookahead ──────────────────
if ! printf '#22D3EEff\n#22D3EE\n' | grep -qP -e '#22D3EE(?![0-9A-Fa-f])'; then
  echo "FATAL: grep -P (PCRE) unavailable or lookahead unsupported."
  echo "       Refusing to run — a degraded pattern would report a false pass."
  exit 2
fi

# ── 1. self-test: every pattern must match known-bad input ───────────────
self_test() {
  local ok=1
  local -a cases=(
    "HEX_RE|#22D3EE|plain v1 hex"
    "HEX_RE|color: #fbbf24;|lowercase v1 hex"
    "HEX_RE|#22d3ee33|8-digit v1 hex with alpha"
    "RGB_RE|rgba(34, 211, 238, 0.1)|comma rgba"
    "RGB_RE|rgb(34 211 238 / 0.07)|space-separated rgb"
    "RGB_RE|rgba(251,191,36,0.35)|comma rgba, no spaces"
    "BINDINGS_RE|  --terra: #A78BFA;|v2 hex re-bound to the v1 quantity"
  )
  for c in "${cases[@]}"; do
    IFS='|' read -r pat input label <<<"$c"
    if printf '%s\n' "$input" | grep -qP -e "${!pat}"; then
      note "ok    $label"
    else
      note "BROKEN $label — pattern $pat no longer matches '$input'"; ok=0
    fi
  done
  # And must NOT match things that are fine.
  local -a negatives=(
    "HEX_RE|#45E0A8|v2 mint"
    "HEX_RE|#22D3EEFF00|longer hex run, not a colour"
    "BINDINGS_RE|  --kw-docking: #A78BFA;|legitimate v2 token"
  )
  for c in "${negatives[@]}"; do
    IFS='|' read -r pat input label <<<"$c"
    if printf '%s\n' "$input" | grep -qP -e "${!pat}"; then
      note "BROKEN $label — pattern $pat false-positives on '$input'"; ok=0
    else
      note "ok    $label (correctly ignored)"
    fi
  done
  [ "$ok" = 1 ] || { echo "self-test FAILED — the checks below cannot be trusted."; exit 2; }
}

echo "── self-test"
self_test
if [ "${1:-}" = "--self-test" ]; then echo; echo "self-test passed."; exit 0; fi

# ── 2. scan ──────────────────────────────────────────────────────────────
echo
echo "── scanning tracked files"
files=$(git ls-files | grep -vE "$EXCLUDE_RE" | grep -vE "$BINARY_RE" || true)
echo "  $(printf '%s\n' "$files" | grep -c . ) files in scope"

# Emit "file:line:text" for every line NOT inside an ignore block.
scannable() {
  printf '%s\n' "$files" | while IFS= read -r f; do
    [ -n "$f" ] || continue
    awk -v F="$f" -v S="$IGNORE_START" -v E="$IGNORE_END" '
      index($0,S) { skip=1 }
      !skip       { printf "%s:%d:%s\n", F, NR, $0 }
      index($0,E) { skip=0 }
    ' "$f" 2>/dev/null
  done
}

scan() {
  local re="$1" label="$2"
  local hits
  hits=$(scannable | grep -aP -e "$re" || true)
  if [ -n "$hits" ]; then
    echo
    echo "  FAIL  $label"
    printf '%s\n' "$hits" | sed 's/^/        /' | cut -c1-160
    fail=1
  else
    echo "  PASS  $label"
  fi
}

scan "$HEX_RE"      "no retired v1 hex literals"
scan "$RGB_RE"      "no v1 rgb()/rgba() triples"
scan "$BINDINGS_RE" "no v2 colour bound to a v1 quantity"

echo
if [ "$fail" = 0 ]; then
  echo "palette v2: clean."
else
  echo "palette v2: violations found (see above)."
  echo "Mapping: teal #22D3EE -> mint #45E0A8 (ΔH) · terra -> violet #8B5CF6 (TΔS)"
  echo "         gold #FBBF24 -> tangerine #FF9300 (ΔG) · ink #0a0e14 -> #08091A"
fi
exit "$fail"
